### ISSUE TITLE
Address remaining comments on PR

### ISSUE THREAD

**Issue by skeating** [inform-health-informatics/Inform-DB#120]
https://github.com/inform-health-informatics/Inform-DB/pull/112

- [x] Avoid cascading deletes (or cascading altogether?) as per Stef's comment - requires controller changes
- [ ] What changes does Sarah require?
- [x] Strongly consider deleting `FormDefinitionFormQuestion` if Jon and Jeremy are in agreement (currently clearing up over email, see https://github.com/inform-health-informatics/emap_planning/issues/52 )
- [x] Rebase (should be trivial)
- [x] Re-request reviews when done

**Comment by jeremyestein** [comment]
- [ ] Avoid cascading deletes (or cascading altogether?) - requires controller changes
- [ ] Re-request reviews
- [ ] What changes does Sarah require?
- [ ] Strongly consider deleting `FormDefinitionFormQuestion` since Jon and Jeremy are in agreement.
- [ ] Rebase (should be trivial)

**Comment by skeating** [comment]
Done and merged
