### ISSUE TITLE
List of possible inconsistencies and improvements to schema.

### ISSUE THREAD

**Issue by jongillham** [inform-health-informatics/Inform-DB#15]
- Should all primary keys just be called `id`. For example instead of `attribute.attribute_id` you would have `attribute.id` instead?
- Should all primary keys be `bigint`? For example `mrn.mrn_id` is an `integer`, `attribute.attribute_id` is a `bigint`.
- Should all `timestamp` fields have common naming conventions? For example `mrn.create_datetime` and `attribute.added_time` appear to represent the same concept. Maybe they should both be called `create_datetime` or `added_datetime` or something else that is consistent between tables.

- `attribute.result_type` could be changed to a string. It is currently an integer enum.
- `patient_fact.fact_id` should be either `patient_fact.patient_fact_id` to be consistent or `patient_fact.id` if we go with primary keys being called `id`.

- `patient_fact.fact_type` could be changed to `patient_fact.attribute_id` to better show what it is connected to.

- Could change `patient_fact.encounter` to reference `patient_fact.encounter_id` to reference the `encounter` primary key instead of its `varchar` field.

- `patient_property.value_as_attribute` or `patient_property.attribute` seems redundant.

- Consider calling `patient_property.parent_fact` `patient_property.patient_fact`.

- Create indexes on all the `patient_property.value_as_*` columns.

- Consider changing `person_mrn.mrn` to `person_mrn.mrn_id` and `person_mrn.person` to `person_mrn.person_id`.

- Should we have `stored_from` and `stored_until` on all tables so we can rerun the history in its entirety?

- Should we be consistent with how we name individuals? Either use person or patient, not both. (Maybe they mean two different things here.)

**Comment by stefpiatek** [comment]
Overall seems sensible, I suppose it'll just be a fair bit of changes to the existing codebase using the database. Only one direct comment on the list, I imagine that the MRN is a constrained length by EPIC and that may explain why that's an integer? 
> * Should all primary keys be `bigint`? For example `mrn.mrn_id` is an `integer`, `attribute.attribute_id` is a `bigint`.

**Comment by jeremyestein** [comment]
Old-style MRNs can have letters and symbols in. I wouldn't want to spend too much time working out exactly how many MRNs are possible when we could just be consistent and use bigint. Also MRNs could get deleted and recreated so we'll need more IDs than MRNs. And currently all ID columns are getting assigned from a single sequence which is a bigint, so it needs to be able to accept bigints. Unless it really makes a big difference to performance or storage I would change it.

**Comment by klapaukh** [comment]
They are all `bigint` so bringing mrn ids inline seems more sensible.

We should also change `patient_fact.encounter` to use the encounter key, not the value.

**Comment by klapaukh** [comment]
> Should all primary keys just be called id. For example instead of attribute.attribute_id you would have attribute.id instead?

This one I'm not sure I'm sold on. I've seen it done before, but I think it is a pain because it means that  when you do a join disambiguating ids is annoying (since all ids have the same name, even though they have the different meaning). I like how Caboodle does it to be fair.

**Comment by jeremyestein** [comment]
What do you think about on the Java side? ie. getPersonMrnId() vs getId()

**Comment by jeremyestein** [comment]
Re mrn.create_datetime vs attribute.added_time. Attribute time is something we have set to a fixed time - the time we decided we needed to add that atttribute. mrn.create_datetime is more like the stored_from in the other fields - if you were to rebuild the database you'd get a new value based on when that MRN was written to the database.
That's what those fields mean - but how should it affect what they are named? Hmm.

**Comment by jeremyestein** [comment]
>     * `patient_fact.fact_type` could be changed to `patient_fact.attribute_id` to better show what it is connected to.

This one I disagree with. The "fact type" is what this field means to patient_fact. The fact it's a link into the attribute table is more an implementation detail - lots of things are attributes. In fact in the patient_property table there are two links into the attributes table but these have quite distinct meanings (key vs value) that are more important than the fact they are attributes.

**Comment by jeremyestein** [comment]
>     * `patient_property.value_as_attribute` or `patient_property.attribute` seems redundant.

The first is the value, the second is the key. (or the "V" and the "A" in EAV, respectively)

**Comment by klapaukh** [comment]
> What do you think about on the Java side? ie. `getPersonMrnId()` vs `getId()`

I think `getId()` is not a problem in Java since there is no ambiguity around joins, and static typing makes it clear what is being referred to. I'm happy for whichever you prefer (as long as it is then consistent everywhere).

**Comment by klapaukh** [comment]
> Re `mrn.create_datetime` vs `attribute.added_time`. Attribute time is manually set to a fixed time - the time we decided we needed to add that atttribute. `mrn.create_datetime` is more like the `stored_from` in the other fields - if you were to rebuild the database you'd get a new value based on when that MRN was written to the database.
> That's what those fields mean - but how should it affect what they are named? Hmm.

Stored_from & Valid_from to match the usage everywhere else?

**Comment by klapaukh** [comment]
> > ```
> > * `patient_fact.fact_type` could be changed to `patient_fact.attribute_id` to better show what it is connected to.
> > ```
> 
> 
> This one I disagree with. 

I agree with Jeremy. Maybe a different solution might be that we should use the `fact_type` notation more consistently? So have `property_type` in patient_property rather than `attribute`?

**Comment by klapaukh** [comment]
> Should we have stored_from and stored_until on all tables so we can rerun the history in its entirety?

It isn't meaningful (or needed) on all tables, e.g. `stored_until` doesn't make sense on `Person`.

**Comment by klapaukh** [comment]
> Should we be consistent with how we name individuals? Either use person or patient, not both. (Maybe they mean two different things here.)

They should be referring to slightly different things.  Persons should be real people while Patients should be more like an 'administrative unit' that is a movable fragment of a real person.

**Comment by stefpiatek** [comment]
I think this has been resolved
