### ISSUE TITLE
Consistent naming of datetime attributes

### ISSUE THREAD

**Issue by AnikaC-git** [inform-health-informatics/Inform-DB#88]
At the moment we unfortunately have an inconsistent naming of attributes that contain both date and time information, some being referred to as e.g. "statusChangeTime", which is elsewhere "statusChangeDatetime". It would be beneficial to consistently name these attributes and change all occurrence that are inconsistent.

**Comment by t-young31** [comment]
From planner:

> We should have some tests that any entitiy field in InformDb that has a type Instant should end with Datetime (e.g. not Time, DateTime)
